### PR TITLE
Remove Map shim

### PR DESCRIPTION
**Pull request by ThomasR**
Fix estools/esshorten#13

### CODE REVIEW

**Comment by michaelficarra** [comment]
I think the reason this shim was being used was for ES3 support. `Object.create` was added in ES5. I'll let @Constellation decide whether we're okay merging this. We'll probably need to make a major version bump if we do.

**Comment by ThomasR** [comment]
I see. An alternative solution would be to use `{}` instead of `Object.create(null)`, and to be careful with inherited properties:
```
this.map = new Map() -> this.map = {}
this.map.has(name) -> this.map.hasOwnProperty(name)
this.map.get(name) -> this.map.hasOwnProperty(name) ? this.map[name] : undefined
```
But that's somewhat clumsy.

**Comment by Constellation** [comment]
@ThomasR, @michaelficarra:

IIRC, originally, escope takes the similar way as you described. escope has `Map` class that only accepts String for its key.
But I changed it to the current way, b/c I think using a shim is better than creating StringMap in escope. So, I think replacing map-shim with `Object.create(null)` is not very good.

But, moving to ES6 or staying in ES5 is another topic. @michaelficarra, what do you think of?
I think either way is ok.

**Comment by michaelficarra** [comment]
:+1: I think that's the right way forward. We just need to remember to make a major version bump next time we release.

**Comment by Constellation** [comment]
OK :)
So, @ThomasR, could you remove the map-shim and replace it with just using ES6 builtin Map?

**Comment by ThomasR** [comment]
And there you go.
I also created another pull request, where I added tons of ES6 features: #15

**Pull request merged**
